<?php
/** @var \Perspective\CurrentProduct\Block\Index $block */
$viewModel = $block->getViewModel();
?>
<?php

if ($currentProduct = $viewModel->getCurrentProduct()) {
echo $currentProduct->getName() . '<br />';
echo $currentProduct->getSku() . '<br />';
echo $currentProduct->getFinalPrice() . '<br />';
echo $currentProduct->getProductUrl() . '<br />';
print_r ($currentProduct->getCategoryIds()) . '<br />';
}
// print current category data
if ($currentCategory = $viewModel->getCurrentCategory()) {
echo $currentCategory->getName() . '<br />';
echo $currentCategory->getUrl() . '<br />';
}
?>